stages:
    - build_and_test

build_jessie-gcc48:
    image: debian:jessie
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-4.8 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_jessie-gcc49:
    image: debian:jessie
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-4.9 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-gcc63:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-6 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-clang38:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-3.8 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-clang39:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-3.9 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_centos7-clang4:
    image: cern/cc7-base
    before_script:
        - yum -q -y install deltarpm
        - yum update -q -y
        - yum install -q -y git cmake3 make boost-devel devtoolset-7-llvm
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; source /opt/rh/llvm-toolset-7/enable; cmake3 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_centos7-gcc72:
    image: cern/cc7-base
    before_script:
        - yum -q -y install deltarpm
        - yum update -q -y
        - yum install -q -y git cmake3 make boost-devel devtoolset-7-gcc-c++
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; source /opt/rh/devtoolset-7/enable; cmake3 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang40:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-4.0 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang40-libc++:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-4.0 libboost-all-dev libc++-dev
    stage: build_and_test
    script:
        - echo 'add_compile_options(-stdlib=libc++)' >> CMakeLists.txt
        - echo 'set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")' >> CMakeLists.txt
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang50:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-5.0 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang50-libc++:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-5.0 libboost-all-dev libc++-dev
    stage: build_and_test
    script:
        - echo 'add_compile_options(-stdlib=libc++)' >> CMakeLists.txt
        - echo 'set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")' >> CMakeLists.txt
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang60:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-6.0 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang60-libc++:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-6.0 libboost-all-dev libc++-dev
    stage: build_and_test
    script:
        - echo 'add_compile_options(-stdlib=libc++)' >> CMakeLists.txt
        - echo 'set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")' >> CMakeLists.txt
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang7:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-7 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_sid-clang7-libc++:
    image: debian:sid
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-7 libboost-all-dev libc++-dev
    stage: build_and_test
    script:
        - echo 'add_compile_options(-stdlib=libc++)' >> CMakeLists.txt
        - echo 'set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")' >> CMakeLists.txt
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

