stages:
    - build_and_test

build_jessie-gcc48:
    image: debian:jessie
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-4.8 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_jessie-gcc49:
    image: debian:jessie
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-4.9 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-gcc63:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake g\+\+-6 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-clang38:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-3.8 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_stretch-clang39:
    image: debian:stretch
    before_script:
        - apt-get update
        - apt-get install -y git cmake clang-3.9 libboost-all-dev
    stage: build_and_test
    script:
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_centos7-clang4:
    image: cern/cc7-base
    before_script:
        - yum -q -y install deltarpm
        - yum update -q -y
        - yum install -q -y git cmake3 make boost-devel devtoolset-7-llvm
    stage: build_and_test
    script:
        - source /opt/rh/llvm-toolset-7/enable
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake3 -DCMAKE_C_COMPILER=`which clang` -DCMAKE_CXX_COMPILER=`which clang++` ..)
        - (cd builddir; make)
        - (cd builddir; make test)

build_centos7-gcc72:
    image: cern/cc7-base
    before_script:
        - yum -q -y install deltarpm
        - yum update -q -y
        - yum install -q -y git cmake3 make boost-devel devtoolset-7-gcc-c++
    stage: build_and_test
    script:
        - source /opt/rh/devtoolset-7/enable
        - git submodule update --init
        - mkdir builddir
        - (cd builddir; cmake3 -DCMAKE_C_COMPILER=`which gcc` -DCMAKE_CXX_COMPILER=`which g++` ..)
        - (cd builddir; make)
        - (cd builddir; make test)

